package br.com.atividade02maven;

import java.util.List;
import javax.swing.JOptionPane;
import br.com.atividade02maven.classes.Filmes;
import br.com.atividade02maven.classes.FilmesDao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patri
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomeFilmePesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DataLancamentoPesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CategoriaPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnPesquisar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do Filme :");

        NomeFilmePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFilmePesquisaActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de Lançamento :");

        jLabel3.setText("Categoria :");

        CategoriaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaPesquisaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data Lançamento", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Dados");

        jLabel5.setText("Filtros: ");

        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(DataLancamentoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(NomeFilmePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(CategoriaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(BtnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtualizar)))
                        .addGap(18, 18, 18)
                        .addComponent(BtnVoltar)
                        .addGap(1, 1, 1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomeFilmePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataLancamentoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPesquisar)
                    .addComponent(BtnVoltar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaPesquisaActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        try {
        String nome = NomeFilmePesquisa.getText(); // Obtém o valor digitado no campo de texto Nome do Filme
        String dataLancamento = DataLancamentoPesquisa.getText(); // Obtém o valor digitado no campo de texto Data de Lançamento
        String categoria = CategoriaPesquisa.getText(); // Obtém o valor digitado no campo de texto Categoria

        FilmesDao filmesDao = new FilmesDao();

        // Verifica se pelo menos um dos campos de filtro foi preenchido
        if (!nome.isEmpty() || !dataLancamento.isEmpty() || !categoria.isEmpty()) {
            List<Filmes> filmes = filmesDao.buscarPorFiltros(nome, dataLancamento, categoria);
            preencheTabela(filmes);
        } else {
            JOptionPane.showMessageDialog(this, "Preencha pelo menos um campo de filtro.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
    }
    }

    private void preencheTabela(List<Filmes> filmes) {
        String[] colunas = {"Nome", "Data Lançamento", "Categoria"};
        String[][] dados = new String[filmes.size()][3];

        for (int i = 0; i < filmes.size(); i++) {
            dados[i][0] = filmes.get(i).getNome();
            dados[i][1] = filmes.get(i).getData().toString(); // Certifique-se de que getDataLancamento() retorna uma String
            dados[i][2] = filmes.get(i).getCategoria();
        }

        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        jTable1.setModel(model);
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
    if (jTable1.getSelectedRow() >= 0) { 
        String nomeFilme = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o filme " + nomeFilme + "?");

        if (resposta == 0) { 
            FilmesDao filmesDao = new FilmesDao();
            filmesDao.excluirPorNome(nomeFilme);
            JOptionPane.showMessageDialog(this, "Filme excluído com sucesso");
            BtnPesquisarActionPerformed(evt);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um filme para excluir.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
}
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada >= 0) {
            String novoNome = JOptionPane.showInputDialog(this, "Novo Nome:");
            String novaData = JOptionPane.showInputDialog(this, "Nova Data de Lançamento:");
            String novaCategoria = JOptionPane.showInputDialog(this, "Nova Categoria:");

            if (novoNome != null && novaData != null && novaCategoria != null) {
                FilmesDao filmesDao = new FilmesDao();

                try {
                    List<Filmes> filmes = filmesDao.listar();
                    Filmes filme = filmes.get(linhaSelecionada);

                    if (!novoNome.isEmpty()) {
                        filme.setNome(novoNome);
                    }

                    if (!novaData.isEmpty()) {
                        // Você precisa converter a novaData para o formato correto (ex: Date)
                        // Exemplo: Date novaDataFormatada = new SimpleDateFormat("dd/MM/yyyy").parse(novaData);
                        // filme.setData(novaDataFormatada);
                    }

                    if (!novaCategoria.isEmpty()) {
                        filme.setCategoria(novaCategoria);
                    }

                    filmesDao.atualizar(filme);

                    // Atualiza a tabela
                    BtnPesquisarActionPerformed(evt);

                    JOptionPane.showMessageDialog(this, "Dados do filme atualizados com sucesso!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um filme para atualizar os dados.");
    }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void NomeFilmePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFilmePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFilmePesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JTextField CategoriaPesquisa;
    private javax.swing.JTextField DataLancamentoPesquisa;
    private javax.swing.JTextField NomeFilmePesquisa;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
