package br.com.atividade03;

import java.util.List;
import javax.swing.JOptionPane;
import br.com.atividade03maven.classes.Podcast;
import br.com.atividade03maven.classes.PodcastDao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patri
 */
public class ConsultaPodCast extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public ConsultaPodCast() {
        initComponents();
   
         try {
            PodcastDao podcastDao = new PodcastDao();
            List<Podcast> podcasts = podcastDao.listar();
            preencheTabela(podcasts);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        produtorTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeEpisodioTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numeroEpisodioTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnPesquisar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do Podcast :");

        produtorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtorTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Episodio :");

        jLabel3.setText("Numero episdio : ");

        numeroEpisodioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroEpisodioTextFieldActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Podcast", "Nome do Episódio", "Número do Episódio", "Duração", "URL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Dados");

        jLabel5.setText("Filtros: ");

        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(numeroEpisodioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(produtorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                            .addComponent(nomeEpisodioTextField))))
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(BtnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(btnAtualizar)
                                .addGap(18, 18, 18)))
                        .addComponent(BtnVoltar)
                        .addGap(1, 1, 1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(produtorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeEpisodioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(numeroEpisodioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPesquisar)
                    .addComponent(BtnVoltar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroEpisodioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroEpisodioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroEpisodioTextFieldActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        try {
            String nome = produtorTextField.getText();
            String nomeEpisodio = nomeEpisodioTextField.getText();
            String numeroEpisodioStr = numeroEpisodioTextField.getText();

            int numeroEpisodio = 0;
            if (!numeroEpisodioStr.isEmpty()) {
                numeroEpisodio = Integer.parseInt(numeroEpisodioStr);
            }

            PodcastDao podcastDao = new PodcastDao();

            // Verifica se pelo menos um dos campos de filtro foi preenchido
            if (!nome.isEmpty() || !nomeEpisodio.isEmpty() || numeroEpisodio > 0) {
                List<Podcast> podcasts = podcastDao.buscarPorFiltros(nome, nomeEpisodio, numeroEpisodio);
                preencheTabela(podcasts);
            } else {
                JOptionPane.showMessageDialog(this, "Preencha pelo menos um campo de filtro.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    }

    private void preencheTabela(List<Podcast> podcasts) {
        String[] colunas = {"Nome do Podcast", "Nome do Episódio", "Número do Episódio", "Duração", "URL"};
        String[][] dados = new String[podcasts.size()][5];

        for (int i = 0; i < podcasts.size(); i++) {
            Podcast podcast = podcasts.get(i);
            dados[i][0] = podcast.getNome();
            dados[i][1] = podcast.getNomeEpisodio();
            dados[i][2] = String.valueOf(podcast.getNumeroEpisodio()); // Converte para String
            dados[i][3] = podcast.getDuracao();
            dados[i][4] = podcast.getUrlRepositorio();
        }

        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        jTable1.setModel(model);
    
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (jTable1.getSelectedRow() >= 0) {
                String nomeFilme = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o filme " + nomeFilme + "?");

                if (resposta == 0) {
                    PodcastDao podcastDao = new PodcastDao();
                    podcastDao.excluirPorNome(nomeFilme);
                    JOptionPane.showMessageDialog(this, "Filme excluído com sucesso");
                    BtnPesquisarActionPerformed(evt);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um filme para excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       int linhaSelecionada = jTable1.getSelectedRow();

if (linhaSelecionada >= 0) {
    String novoNomeEpisodio = JOptionPane.showInputDialog(this, "Novo Nome do Episódio:");
    String novoNumeroEpisodioStr = JOptionPane.showInputDialog(this, "Novo Número do Episódio:");
  

    if (novoNomeEpisodio != null && novoNumeroEpisodioStr != null) {
        PodcastDao podcastDao = new PodcastDao();

        try {
            List<Podcast> podcasts = podcastDao.listar();
            Podcast podcast = podcasts.get(linhaSelecionada);

            if (!novoNomeEpisodio.isEmpty()) {
                podcast.setNomeEpisodio(novoNomeEpisodio);
            }

            if (!novoNumeroEpisodioStr.isEmpty()) {
                int novoNumeroEpisodio = Integer.parseInt(novoNumeroEpisodioStr);
                podcast.setNumeroEpisodio(novoNumeroEpisodio);
            }

            int resultado = podcastDao.atualizar(podcast);

            if (resultado == 1) {
                // Atualiza a tabela
                BtnPesquisarActionPerformed(evt);

                JOptionPane.showMessageDialog(this, "Dados do podcast atualizados com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar os dados do podcast.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Selecione um podcast para atualizar os dados.");
}


    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void produtorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtorTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPodCast.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPodCast.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPodCast.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPodCast.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPodCast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeEpisodioTextField;
    private javax.swing.JTextField numeroEpisodioTextField;
    private javax.swing.JTextField produtorTextField;
    // End of variables declaration//GEN-END:variables
}
